- README.md
WindowsForms-docs readme files
> IN-17762-UG GitHub Edit option changes - Read Me file changes-dev

- WindowsForms/chart/FAQ/How-to-customize-the-data-points-for-Chart-Series.md
Added more information and sample
> WF-62505-Update chart FAQ-Custom datapoints for series

- WindowsForms/MultiColumn-TreeView/Data-Binding.md
Hi @ChristoIssac,
Worked on SIte Audit Issues, merge these changes.
Regards,
Gowthaman
> SEO-1973_Site_Audit_Issues

- WindowsForms/chart/Getting-Started.md
- WindowsForms/chart/Overview.md
WinForms Chart Money Keywords Interlinking
> SEO-1887-WinForms Chart Interlinking

- WindowsForms/Navigation-Drawer/Getting-Started.md
- WindowsForms/Navigation-Drawer/Overview.md
- WindowsForms/Navigation-Drawer/Style.md
WinForms Navigation Drawer Money Keywords Interlinking
> SEO-1944-Interlinking for navigation drawer FT

- WindowsForms/Syntax-Editor/Getting-Started.md
Hi All,
Could you please review and merge the PR
> SEO-1908-winforms-moneykeywords-syntax-editor-docs

- WindowsForms/Scheduler/Customizing-Appearance.md
- WindowsForms/Scheduler/Getting-Started.md
- WindowsForms/Scheduler/Overview.md
Hi All,
Content task :https://syncfusion.atlassian.net/browse/CONTENT-5748
Could please review and merge the below PR's
> SEO-1908-MKW-WF-Scheduler-masterdocs-Onpage-interlink

- WindowsForms/DataGrid/DataBinding.md
- WindowsForms/DataGrid/GettingStarted.md
- WindowsForms/Grid-Control/Getting-Started.md
- WindowsForms/Grid-Control/Performance.md
- WindowsForms/Grid-Control/Populating-Data.md
- WindowsForms/MultiColumn-TreeView/Data-Binding.md
- WindowsForms/MultiColumn-TreeView/Getting-Started.md
- WindowsForms/MultiColumn-TreeView/Overview.md
Hi @ChristoIssac 
I have updated the interlink works for WF Datagrid, Grid and MultiColumnTreeView control.
Please review the changes and merge it.
Regards,
Mallika
> SEO-1955: Need to work Money Keywords - Interlink works

- WindowsForms/Diagram/Getting-Started.md
- WindowsForms/Diagram/Overview.md
Hi @ChristoIssac ,
Please review the changes for WinForms Diagram Interlinking,
Regards,
@Sharly-Atieno
> SEO-1934-WinForms Diagram Interlinking 

- WindowsForms/Pivot-Grid/Editing-Values.md
- WindowsForms/Pivot-Grid/Exporting.md
- WindowsForms/Pivot-Grid/Freezing-Headers.md
- WindowsForms/Pivot-Grid/Getting-Started.md
- WindowsForms/Pivot-Grid/Hyperlink-Cells.md
- WindowsForms/Pivot-Grid/Layouts.md
- WindowsForms/Pivot-Grid/Overview.md
Hi @ChristoIssac ,
Please review the changes for the WinForms pivot grid.
Regards,
@Sharly-Atieno
> SEO-1938 - WinForms pivot grid interlinking changes

- WindowsForms/PDF-Viewer/pdf-rendering-engines.md
Added the UG content about the upgradation of Pdfium DLL.
> WF-62981 Update UG content for Pdfium Rendering engine

- WindowsForms/CheckBox/Text-Settings.md
- WindowsForms/Docking-Manager/FAQ/General/How-to-Enable-the-Tabbed-Style-Dockable-Window-using-TabbedMDI-manager.md
- WindowsForms/Ribbon/Touch-Support.md
Hi @ChristoIssac,
Worked on Bing report issues, merge these changes.
Regards,
Gowthaman
> SEO-2050_Site_Audit_Issues

- README.md
- WindowsForms/Grid-Control/Data-Validation.md
> IN-17762-UG GitHub Edit option changes - Read Me file changes-mas

- WindowsForms/DataGrid/Rows.md
- WindowsForms/ListView/ItemSizing.md
Hi @ChristoIssac,
Worked on Bing report issues, so merge these changes.
Regards,
Gowthaman
> SEO-2111_Site_Audit_Issues

- WindowsForms/DataGrid/Rows.md
- WindowsForms/Diagram/Touch-Support.md
- WindowsForms/TextBox/Applying-Themes.md
- WindowsForms/office2010form/Customization.md
Worked on site audit issues, merge these changes.
Regards,
Gowthaman
> SEO-2190_Site_Audit_Issues

- WindowsForms/DataGrid/ExportToExcel.md
> WF-62535 Correct the VB code snippet in the Excel exporting in SfDataGrid

- WindowsForms/DataGrid/ColumnTypes.md
- WindowsForms/DataGrid/DataValidation.md
- WindowsForms/DataGrid/Editing.md
- WindowsForms/DataGrid/ExportToPDF.md
- WindowsForms/DataGrid/MasterDetailsView.md
- WindowsForms/DataGrid/Paging.md
- WindowsForms/DataGrid/PreviewRows.md
- WindowsForms/DataGrid/Sorting.md
VB code snippets modified properly
> WF-62535 : Contents modified based on feedback

- WindowsForms-toc.html
- WindowsForms/arm-support.md
This PR contains the ARM64 device compatibility related details.
> WINUI-2768 - ARM64 support content

- WindowsForms/Installation/offline-installer/how-to-download.md
- WindowsForms/Installation/web-installer/how-to-download.md
- WindowsForms/Licensing/how-to-generate.md
- WindowsForms/Licensing/licensing-errors.md
- WindowsForms/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md
- WindowsForms/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md
- WindowsForms/Licensing/overview.md
- WindowsForms/Upgrade/how-to-upgrade.md
> IN-18200-UG-Link-Changes-winforms-hotfix

- WindowsForms/Button/Appearance.md
> WF-100 Fix broken link

- WindowsForms/MultiColumn-ComboBox/Event-Handling.md
WF-63937-Changing-the-link-in-Multicolumncombobox
> WF-63937-Changing-the-link-in-Multicolumncombobox

- WindowsForms/System-Requirements.md
I have added the .NET 5 and .NET 6 related details.
> WINUI-2801 - .NET 5 and .NET 6 related details

- WindowsForms/MultiColumn-ComboBox/Event-Handling.md
WF-63937-Link-Correction-in-documentation
> WF-63937-Link-Correction-in-documentation

- WindowsForms/Splash-Screen/SplashControl-Overview.md
- WindowsForms/tabbedmdi/Tab-Groups.md
Worked on site audit issues, merge these changes,
Regards,
Gowthaman
> SEO-2475_Site_Audit_Issues

- WindowsForms/xptaskpane/Creating-a-Simple-XPTaskPane.md
Indent space provided for the XPTaskPane Documentation,
Added the capture tag in the code snippet
> TEST-34253-modify the ident issues in UG documentation

- WindowsForms/ComboBox-DropDown/Getting-Started.md
- WindowsForms/autocomplete/Getting-started.md
-Added the capture tags in code snippet block
-Indent space provided for the autocomplete Documentation
> TEST-34252: Modified the Indent issues in UG Documentation

- WindowsForms/GridGrouping/Advanced-Features.md
> TEST-34253-Corrected the indention issues for WF controls in the UG documentation 

- WindowsForms/GridGrouping/Relations-and-Hierarchy.md
- WindowsForms/GridGrouping/Summaries.md
> TEST-34253-Corrected the indention issues in the UG documentation

- WindowsForms/CheckBox/Alignment-Settings.md
- WindowsForms/GridGrouping/Getting-Started.md
- WindowsForms/layoutmanagers/Layout-Manager-Settings.md
Hi @ChristoIssac,
|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 5 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/windowsforms-docs/pull/340 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman
> SEO-2684-Coverage-report-pages-with-redirect

- WindowsForms/Currency-TextBox/Overview.md
- WindowsForms/Diagram/Getting-Started.md
- WindowsForms/Editable-ListBox/Getting-Started.md
- WindowsForms/Gradient-Label/Serialization.md
- WindowsForms/GridRecordNavigationControl/Overview.md
- WindowsForms/HighDPI-support.md
- WindowsForms/Html-Viewer/HTML-Tags.md
- WindowsForms/Localization.md
- WindowsForms/Syntax-Editor/Getting-Started.md
- WindowsForms/Syntax-Editor/Localization.md
- WindowsForms/Watermark-Text-Provider/Getting-Started.md
- WindowsForms/Watermark-Text-Provider/Overview.md
- WindowsForms/layoutmanagers/FAQ/How-to-layout-non-control-based-Child-components.md
- WindowsForms/layoutmanagers/FAQ/How-to-programmatically-nest-various-layouts.md
--Resolved the indent failures
> TEST-34252 Corrected the indent issues in the UG 

- WindowsForms/Button/Appearance.md
- WindowsForms/Calendar/Getting-Started.md
- WindowsForms/Grid-Control/Getting-Started.md
- WindowsForms/Grid-Control/Scrolling.md
- WindowsForms/GridGrouping/Data-Binding.md
- WindowsForms/GridGrouping/Data-Representation.md
- WindowsForms/GridGrouping/Expression-Fields.md
- WindowsForms/GridGrouping/Summaries.md
- WindowsForms/MultiColumn-TreeView/Appearance.md
- WindowsForms/Navigation-Drawer/Getting-Started.md
- WindowsForms/Radial-Slider/Getting-Started.md
> TEST-34253-Modified the indention issues for WF controls in the UG documentation 

- WindowsForms/Currency-TextBox/Overview.md
- WindowsForms/Diagram/Getting-Started.md
- WindowsForms/Editable-ListBox/Getting-Started.md
- WindowsForms/Gradient-Label/Serialization.md
- WindowsForms/GridRecordNavigationControl/Overview.md
- WindowsForms/HighDPI-support.md
- WindowsForms/Html-Viewer/HTML-Tags.md
- WindowsForms/Localization.md
- WindowsForms/Syntax-Editor/Getting-Started.md
- WindowsForms/Syntax-Editor/Localization.md
- WindowsForms/Watermark-Text-Provider/Getting-Started.md
- WindowsForms/Watermark-Text-Provider/Overview.md
- WindowsForms/layoutmanagers/FAQ/How-to-layout-non-control-based-Child-components.md
- WindowsForms/layoutmanagers/FAQ/How-to-programmatically-nest-various-layouts.md
> TEST-34252 Corrected the indent issues in the UG documentation

- WindowsForms/Grouping/Getting-Started.md
Please review the changes for WindowsForms Image Alt Text.
Regards,
Yvone.
> SEO-2904 WindowsForms Image Alt Text

- WindowsForms/System-Requirements.md
- WindowsForms/dotnet-framework-compatibility.md
Added Net7.0 support details in Winforms UG
> WF-65090 : Added Net7.0 support details in Winforms UG

- WindowsForms/DataGrid/Helpers.md
Updated the Helper method with code snippets.
For more details refer the task
https://syncfusion.atlassian.net/browse/WF-65153
> WF-56119 - Helper method updated with code snippets. 

- WindowsForms/ComboBox-DropDown/ComboDropDown-Appearance.md
- WindowsForms/Integer-TextBox/Overview.md
Hi Aishwarya,
Worked on page with redirect for help links, so merge these changes
Regards,
Gowthaman
> SEO-3146-coverage-page-with-redirect-help

- WindowsForms/layoutmanagers/FlowLayout.md
Please review the changes for Windowsforms Page with redirect.
Regards,
Yvone.
> SEO-3239 Windowsforms Page with redirect

- WindowsForms/Navigation-Pane/GettingStarted.md
Add more information about adding child items in to group bar.
> WF-63960 : Add more information about adding child items to a group in navigation pane

- WindowsForms/Calculation-Engine/getting-started.md
- WindowsForms/Grouping/Getting-Started.md
- WindowsForms/PDF-Viewer/Localization.md
- WindowsForms/Sparkline/GettingStarted.md
Please review changes for Windows Forms controls.
Regards,
Sharly A.
> SEO-3267 - Windows Forms Controls http to https

- WindowsForms/Upgrade/how-to-upgrade.md
Please review permanent redirect changes for WinForms .
Regards,
Sharly A.
> SEO-3353-WinForms

- WindowsForms/Calculation-Engine/getting-started.md
- WindowsForms/CommandBar/Getting-Started.md
- WindowsForms/ContextMenuStrip/Getting-Started.md
- WindowsForms/Grid-Control/Getting-Started.md
- WindowsForms/Map/Getting-Started.md
- WindowsForms/Menu/Getting-Started.md
- WindowsForms/PDF-Viewer/Getting-Started.md
Worked on SEMrush report issues, so merge these changes
Regards,
Gowthaman
> SEO-3261-semrush-report-issues

- WindowsForms/Grid-Control/Performance.md
Please review the changes for WPF Page with redirect.
Regards,
Selline Rita.
> SEO-3233 - WindowForms Page with redirect

- WindowsForms/Overview.md
- WindowsForms/PDF-Viewer/Localization.md
- WindowsForms/Pivot-Chart/Getting-Started.md
- WindowsForms/Pivot-Grid/Getting-Started.md
- WindowsForms/PopupMenu/Getting-Started.md
- WindowsForms/Radial-Gauge/Radial-Gauge.md
- WindowsForms/XPToolbar/Getting-Started.md
Worked on SEMrush issues, so merge these changes
Regards,
Gowthaman
> SEO-3356-semrush-report-issues

- WindowsForms/DICOM/Overview.md
- WindowsForms/Diagram/Overview.md
- WindowsForms/chart/Overview.md
Added redirect link, please review.
Regards,
Sharly A.
> SEO-3380 - WindowsForm Controls redirect link

- WindowsForms/ContextMenuStrip/Display-image-in-menu-items.md
Updated the code snippet for adding the display image for menu items for ContextMenuStripEx.
> WF-63852 : Update the code snippet for adding the display image in menu items for ContextMenuStripEx Control

- WindowsForms/Licensing/how-to-register-in-an-application.md
WF-65738 Include the documentation for Registering License Key in VB projects
UG Document modified for how to register license in the application when we created the Program.vb file.
How to register in the application document
> WF-65738 Include the documentation for Registering License Key in VB projects

- WindowsForms/Grouping/FAQ/How-to-Clear-a-Filter.md
Worked on description is too long short.
Regards,
Sharly A.
> SEO-3353 - WindowsForms

- WindowsForms/DataGrid/ClipboardOperations.md
- WindowsForms/DataGrid/Filtering.md
- WindowsForms/DataGrid/Grouping.md
- WindowsForms/DataGrid/Localization.md
- WindowsForms/DataGrid/MasterDetailsView.md
- WindowsForms/DataGrid/Selection.md
- WindowsForms/DataGrid/Summaries.md
Changed http to https link issues.
Regards,
Sharly A.
> SEO-3446 - WindowsForms Controls

- WindowsForms/Grid-Control/MS-Excel-Like-Features.md
Added redirect links for windowsforms.
Regards,
Sharly A.
> SEO-3446 - WindowsForms redirect links

- WindowsForms/System-Requirements.md
- WindowsForms/arm-support.md
- WindowsForms/dotnet-framework-compatibility.md
I have removed the .Net 2.0 and .Net 3.5 support in Winforms UG
> WF-65817 : Remove the .Net 2.0 and .Net 3.5 support and add the .Net70 support in Winforms and WPF UG

- WindowsForms/Licensing/how-to-generate.md
Have changed redirect link in Windowsforms, please check.
Regards,
Yvone.
> SEO-3445 Windowsforms Redirect

- WindowsForms/System-Requirements.md
- WindowsForms/arm-support.md
- WindowsForms/dotnet-framework-compatibility.md
Please find the development PR,
https://github.com/syncfusion-content/windowsforms-docs/pull/485/files
> WF-65817 : Remove the .Net 2.0 and .Net 3.5 support and add the .Net70 support in Winforms and WPF UG _ Hotfix branch

- WindowsForms/Licensing/how-to-register-in-an-application.md
- WindowsForms/Release-notes/v21.1.35.md
WF-65738 Include the documentation for Registering License Key in VB projects
UG Document modified for how to register license in the application when Program.vb file was entry point of the application.
How to register in the application document
> WF-65738 When program.vb file was entry point, how to register licensing

- WindowsForms/Licensing/how-to-register-in-an-application.md
WF-65738 Include the documentation for Registering License Key in VB projects
UG Document modified for how to register license in the application when we created the Program.vb file.
How to register in the application document
> WF-65738 Final concerns changed

- WindowsForms/ContextMenuStrip/Display-image-in-menu-items.md
Hi, 
I have worked on links with redirects,
Regards,
Beryl
> SEO-3458-Links-With-Redirect-Winforms

- WindowsForms/DataGrid/ExportToPDF.md
- WindowsForms/Grid-Control/Enhanced-Cell-Types.md
- WindowsForms/Metro-Form/Overview.md
Have changed Redirect links.
Regards,
Yvone.
> SEO-3460 WindowsForms Redirect

- WindowsForms/Classic/DataBoundGrid/How-To/How-to-resolveObject-reference-not-set-to-an-instance-of-an-object-error-generation-in-GridDataBoundGrid-Designer.md
- WindowsForms/Grid-Control/TabBarSplitterControl.md
Worked on Bing report issues, so merge these changes
Regards,
Gowthaman
> SEO-3615-bing-issues

- WindowsForms/Button/Appearance.md
- WindowsForms/Docking-Manager/Docking-Events.md
Have changed redirect links.
Regards,
Yvone.
> SEO-171350 WindowsForms Redirect

- WindowsForms/Calculation-Engine/FAQ/Common/How-to-Use-a-Comma-as-a-Decimal-Separator-in-Formu.md
- WindowsForms/GridGrouping/Events.md
- WindowsForms/Visual-Studio-Integration/Troubleshooting.md
Hi @Aishwarya-Ganesan 
I have worked on the links with redirects.
Kind regards,
Beryl.
> SEO-171356-Links-With-Redirects

- WindowsForms/GridGrouping/Grid-Layout.md
Have changed help page with redirect links in WindowsForms.
Regards,
Yvone.
> SEO-171350 WindowsForms Page with redirect links

- WindowsForms/DataGrid/Grouping.md
Have changed Windowsforms redirect links, please review.
Regards,
Yvone.
> SEO-171762 Windowsforms Redirect

- WindowsForms/chart/Chart-Axes.md
**Description**
I have added how to hide the axis label in axis.
> WF-827842-Add more information about axis label.

- WindowsForms/Calendar/Overview.md
- WindowsForms/ContextMenuStrip/Appearance-Customization.md
- WindowsForms/DataGrid/InteractiveFeatures.MD
- WindowsForms/Grid-Control/Cell-Style-Architecture.md
- WindowsForms/Grid-Control/Virtual-Grid.md
HI @Aishwarya-Ganesan ,
Please review changes for Window Forms redirect links.
Regards,
Selline Rita.
> SEO-171714 - Window Forms Page with redirect  

- WindowsForms/Grid-Control/Covered-Ranges.md
- WindowsForms/SplitContainer/SplitContainerAdv.md
- WindowsForms/Tab-Splitter-Container/Splitter-Components.md
Have made changes in redirect links, kindly review.
Thanks.
Regards,
Edith.
> SEO-172121 -Windowsforms controls-Redirect links

- WindowsForms/Syntax-Editor/syntax-highlighting.md
- WindowsForms/Tooltip/Overview.md
Worked on weblink page with redirect links for WinForms. Kindly review.
Regards,
Sharly A.
> SEO-172146 - WinForms Controls Weblinks

- WindowsForms/DataGrid/Selection.md
- WindowsForms/DataGrid/Styling.md
- WindowsForms/DataGrid/Summaries.md
- WindowsForms/Form/Overview.md
- WindowsForms/Form/TitleBar.md
Have changed redirect links in Windowsforms, please review.
Regards,
Yvone.
> SEO-172160-Windowsforms-redirect-links

- WindowsForms/DataGrid/ExportToExcel.md
- WindowsForms/DataGrid/ExportToPDF.md
- WindowsForms/DataGrid/Grouping.md
- WindowsForms/DataGrid/Overview.md
- WindowsForms/DataGrid/Rows.md
Have changed redirect links in Windowsforms, please review.
Regards,
Yvone.
> SEO-172160-Wndowsforms-redirect

- WindowsForms/PDF-Viewer/pdf-rendering-engines.md
Added the Pdfium upgradation details for the Pdfviewer.
> Added the Pdfium Upgradation details for PdfViewer

- WindowsForms/Classic/DateTimePicker/Overview.md
- WindowsForms/Classic/Month-Calendar/Overview.md
- WindowsForms/Classic/MultiSelectionComboBox/Overview.md
- WindowsForms/ComboBox/Overview.md
- WindowsForms/DataGrid/ColumnTypes.md
Have changed redirect links, please review.
Regards,
Yvone.
> SEO-172160 Windowsforms weblink

- WindowsForms/Overview.md
| Title | Description |
| -------- | -------- |
|**Task Link**|https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/174643|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Changed the col width in the introduction.md file|
|**Output screenshots**||
|**Areas affected and ensured**|<ul><li>Changes in the introduction.md file. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new …
> 174643-Tabletextalignmentissue-dev

- WindowsForms/Overview.md
| Title | Description |
| -------- | -------- |
|**Task Link**|https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/175165|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Changed the col width in the overview.md file|
|**Output screenshots**|-|
|**Areas affected and ensured**|<ul><li>Changes in the introduction.md file. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new code …
> 174643-Tabletextalignmentissue-hotfix

- WindowsForms/ContextMenuStrip/Appearance-Customization.md
- WindowsForms/ContextMenuStrip/Render-Mode.md
- WindowsForms/DataGrid/ClipboardOperations.md
- WindowsForms/DataGrid/DataBinding.md
Have changed Page with redirect links.
Regards,
Yvone.
> SEO-174775 WF Page with Redirect links

- WindowsForms-toc.html
Adding XlsIO in Windows Forms UG
> 847601 - Add XlsIO in WinForms UG - HF

- WindowsForms/Control-Dependencies.md
- WindowsForms/PDF-Viewer/Getting-Started.md
UG Content for PdfToImageConverter
> UG Content for PdfToImageConverter

- WindowsForms-toc.html
Hi all,
- With this PR, we have added DocIO & Presentation controls in windows form platform UG.
Regards,
Dharanitharan A
> ES-846833-Add DocIO & Presentation controls in windows form platform UG-hotfix

- WindowsForms/DataGrid/ColumnTypes.md
- WindowsForms/Grid-Control/Find-and-Replace.md
- WindowsForms/Grid-Control/Printing.md
- WindowsForms/ListView/Localization.md
- WindowsForms/Radial-Gauge/Radial-Gauge.md
- WindowsForms/Smith-Chart/Axes.md
Have changed WindowsForms Page with Redirect UG.
Regards,
Yvone.
> SEO-175659 Windows Forms Redirect

- WindowsForms-toc.html
Hi all,
- With this PR, we have modified the DocIO and Presentation page navigation link.
Regards,
Dharanitharan A
> ES-846833-Modified the DocIO and Presentation page navigation link

- WindowsForms/Grid-Control/Selection.md
- WindowsForms/GridGrouping/Zooming.md
Have changed Page with Redirect links.
Regards,
Yvone.
> SEO-175659 WF Page with Redirect.

- WindowsForms-toc.html
Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh
> ES-851567 Modify TOC File

- WindowsForms/ComboBox/DataBinding.md
- WindowsForms/ComboBox/DropDown.md
- WindowsForms/ComboBox/UIAutomation.md
- WindowsForms/Navigation-Drawer/Events.md
- WindowsForms/Navigation-Pane/Control-Overview.md
- WindowsForms/Navigation-Pane/GroupBar-Events.md
- WindowsForms/Navigation-Pane/Header-Customization-Settings.md
Hi @MallikaRK ,
Worked on page with redirect for WF Controls.
Regards,
Sharly A.
> SEO-176126 - WF Page with redirect

- WindowsForms/Overview.md
- WindowsForms/right-to-left.md
Hi @MallikaRK ,
Worked on windowsforms sub pages.
Regards,
Sharly A.
> SEO-176556 - WF feature changes

- WindowsForms/ComboBox/UIAutomation.md
- WindowsForms/DataGrid/MasterDetailsView.md
- WindowsForms/Grid-Control/Populating-Data.md
- WindowsForms/GridGrouping/Grid-Designer.md
- WindowsForms/Tabbed-Form/TabNavigation.md
- WindowsForms/groupview/FAQ/How-to-drag-and-drop-a-GroupView-Item-into-any-other-control-ListView-control.md
Have worked on changing Page with Redirect links.
Regards,
> SEO-176130 WindowsForms Redirect

- WindowsForms/Grid-Control/Cell-Navigation.md
- WindowsForms/Scroll-Frame/ContextMenu.md
- WindowsForms/Scroll-Frame/Localization.md
- WindowsForms/Scroll-Frame/UIAutomation.md
- WindowsForms/Spell-Checker/VisualStyle.md
- WindowsForms/SplitContainer/Events.md
- WindowsForms/Spreadsheet/Conditional-Formatting.md
- WindowsForms/Spreadsheet/Custom-Formula.md
- WindowsForms/Spreadsheet/Data-Management.md
- WindowsForms/Spreadsheet/Editing.md
Have worked on Page with Redirect.
Regards,
Yvone.
> SEO-176507 WindowsForms Page Redirect

- WindowsForms/GridGrouping/Filtering.md
- WindowsForms/GridGrouping/Grid-Layout.md
Hi @MallikaRK ,
Have made changes on the redirect links. Please review.
Thanks.
Regards,
Edith.
> SEO-175680-Windowsforms-UG-page-with-redirects-link

- WindowsForms-toc.html
I have added XlsIO control UG redirect links.
> 854120 - XlsIOChanges - WinForms

- WindowsForms/Visual-Studio-Integration/Add-References.md
- WindowsForms/Visual-Studio-Integration/Create-Project.md
I have modified the UG content
> EXT-1775-Modified the UG content

- WindowsForms/System-Requirements.md
- WindowsForms/dotnet-framework-compatibility.md
[UG documentation 857310](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/857310): Need to update the Windows Forms UG
1. I have updated the .NET8.0 in System Requirements.
2. I have updated the .NET8.0 in **23.2 version Vol 3** in Version Compatibility.
3. I have Updated the .NET8.0 status for Control Compatibility.
> ES-857310 - Need to update the Windows Forms UG

- WindowsForms/dotnet-framework-compatibility.md
[UG documentation 857310](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/857310): Need to update the Windows Forms UG
- Updated the column span  for the Control Compatibility in the .Net Framework Compatibility documentation.
> ES-857310- Updated the column span in the .Net Framework Compatibility documentation

- WindowsForms/ListView/UIAutomation.md
- WindowsForms/MaskedTextBox/Display-Settings.md
- WindowsForms/MaskedTextBox/MaskedEditBox-Events.md
- WindowsForms/Menu/Appearance-Customization.md
- WindowsForms/Menu/MDI-Child-Forms.md
- WindowsForms/MessageBox/Button-Parameters.md
HI @MallikaRK ,
Please review the redirect UG links changes.
Thanks.
Regards,
Edith.
> SEO-176497-WinForms-redirect-UG-link

- WindowsForms/Licensing/how-to-generate.md
- WindowsForms/Licensing/licensing-errors.md
- WindowsForms/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md
- WindowsForms/Licensing/licensing-faq/where-can-i-get-a-license-key.md
- WindowsForms/Licensing/overview.md
- WindowsForms/layoutmanagers/BorderLayout.md
- WindowsForms/layoutmanagers/CardLayout.md
- WindowsForms/layoutmanagers/FlowLayout.md
- WindowsForms/layoutmanagers/GridBagLayout.md
- WindowsForms/layoutmanagers/GridLayout.md
HI @MallikaRK ,
Please review the redirect UG links changes.
Thanks.
Regards,
Edith.
> SEO-176497-WinForms-redirect-UG-links

- WindowsForms/ContextMenuStrip/Trigger-Menu-Items.md
- WindowsForms/Currency-TextBox/Advanced-Features.md
- WindowsForms/Currency-TextBox/Appearance.md
- WindowsForms/Currency-TextBox/Event-Handling.md
- WindowsForms/Currency-TextBox/Text-Field.md
Hello,
I have worked on the links with redirects.
Regards,
Beryl.
> SEO-176113-Pages-With-Redirects-WF1

- WindowsForms/CommandBar/Appearance-Customization.md
- WindowsForms/ContextMenuStrip/CheckedState-of-menu-items.md
- WindowsForms/ContextMenuStrip/Disable-menu-items.md
- WindowsForms/ContextMenuStrip/Keyboard-Shortcuts.md
- WindowsForms/ContextMenuStrip/Margin-and-Shadow.md
- WindowsForms/ContextMenuStrip/Multilevel-Menu-Items.md
- WindowsForms/ContextMenuStrip/RTL.md
Hello,
I have worked on the links with redirects.
Regards,
Beryl.
> SEO-176113-Pages-With-Redirects-WF

- WindowsForms/Radial-Slider/Slider-customization.md
- WindowsForms/Range-Slider/Interactive-Features.md
- WindowsForms/Rating-Control/Styling.md
- WindowsForms/Scroll-Frame/Localization.md
Hello,
I have worked on the links with redirects.
Regards,
Beryl.
> SEO-176113-Pages-With-Redirects

- WindowsForms/GridGrouping/FAQ/Selections/What-are-the-events-fired-when-the-records-are-selected.md
ES - 815480 - I have added the selection events-related content to GridGroupingControl FAQ page
> ES - 815480 - Updated the content

- WindowsForms/GridGrouping/Exporting.md
- WindowsForms/GridGrouping/Expression-Fields.md
- WindowsForms/GridGrouping/FindAndReplace.md
- WindowsForms/GridGrouping/Grouping.md
- WindowsForms/GridGrouping/Navigation-Bar.md
- WindowsForms/GridGrouping/Printing.md
- WindowsForms/GridGrouping/Relations-and-Hierarchy.md
Hello,
I have worked on links with redirects.
Kind regards,
Beryl
> SEO-176113-Pages-With-Redirects-WinForms1

- WindowsForms/Popup/Getting-Started.md
- WindowsForms/Popup/Hosting-ComboBoxBase-Control.md
- WindowsForms/Popup/How-to-Get-Around-this-Behavior.md
- WindowsForms/Popup/Keyboard-Navigation.md
- WindowsForms/Popup/RTL.md
- WindowsForms/PopupMenu/Checked-or-unchecked-bar-items.md
- WindowsForms/PopupMenu/Events.md
- WindowsForms/PopupMenu/Touch-and-Keyboard.md
- WindowsForms/PopupMenu/Trigger-Bar-Item.md
Hi @MallikaRK, have updated the redirect links, please review.
Thanks.
Regards,
Edith
> SEO-176062-WinForms-redirect-UG-links-

- WindowsForms/Grid-Control/Appearance-and-Formatting.md
- WindowsForms/Grid-Control/Cell-Types.md
Have changed Page with Redirect links.
Regards,
Yvone.
> SEO-178113 WindowsForms Page with Redirect

- WindowsForms/Visual-Studio-Integration/Create-Project.md
- WindowsForms/Visual-Studio-Integration/Item-Template.md
- WindowsForms/Visual-Studio-Integration/Template-Studio.md
I have committed the WF Template Studio  and WF ItemTemplate UG content changes.
> EXT-175791 WinForm Extension UG updated

- WindowsForms/DataGrid/Localization.md
Hello,
I have worked on links with redirects.
Regards,
Beryl.
> SEO-178943-Redirect-Links-WF1

- WindowsForms/Grid-Control/Cell-Merging.md
- WindowsForms/Grid-Control/Scrolling.md
Hello,
I have worked on links with redirects.
Regards,
Beryl.
> SEO-178943-WF-Redirect-Links

- WindowsForms/DateTimePicker/Appearance.md
I have worked on redirection links, please review.
Regards,
Scholar.
> SEO-179238-Page-with-redirect

- WindowsForms/Installation/web-installer/how-to-download.md
Have changed Page with Redirect links.
Regards,
Yvone.
> SEO-179238 WindowsForms Page with Redirect

- WindowsForms/Grid-Control/FormulaBar.md
- WindowsForms/Pivot-Grid/Localization.md
- WindowsForms/Section508Compliance/VPAT.md
Hi @MallikaRK 
Kindly review my PR below.
Regards 
Dickson J
> SEO-174654-WindowsForms-SectionA

- WindowsForms/PDF-Viewer/Getting-Started.md
871185 Add code snippet on Pdfviewer code behind.
> 871185 Add code snippet on Pdfviewer code behind.

- WindowsForms/XPToolbar/RTL.md
Hi @MallikaRK ,
Worked on windowsforms changes.
Regards,
Sharly A.
> SEO-180850-WindowsForms-changes

- WindowsForms/Ribbon/Appearance.md
Added the UG documentation for the newly implemented HoverColor support for ToolStripButton through Office2016 colortable in RibbonControlAdv
> WF-869120-Updated the UG documentation for the HoverColor feature

- WindowsForms/PDF-Viewer/Getting-Started.md
Updated the missing code changes in WinForms
> Updated the missing code changes in WinForms

- WindowsForms/Installation/install-nuget-packages.md
- WindowsForms/XPToolbar/RTL.md
Hi @MallikaRK,
Worked on windows forms changes.
Regards,
Sharly A.
> SEO-180850-WindowsForms-docs-changes

- WindowsForms/Diagram/Data-Binding.md
- WindowsForms/Grid-Control/Selection.md
- WindowsForms/Grid-Control/Zooming.md
Hi @MallikaRK,
Worked on Windows Forms-Changes.
Regards,
Sharly A.
> SEO-181938-WindowsForms-Changes

- WindowsForms/Spreadsheet/Conversion.md
- WindowsForms/Spreadsheet/Worksheet-Management.md
Hi @MallikaRK,
Worked on Windows Forms-Changes.
Regards,
Sharly A.
> SEO-181938-WindowsForms-Changes-2

- WindowsForms/ComboBox/Localization.md
- WindowsForms/DataGrid/Filtering.md
Hi @MallikaRK,
I have fixed the http issues, please review.
Regards,
Scholar.
> SEO-181471-WF-HTTP-TO-HTTPS

- WindowsForms/DataGrid/Columns.md
- WindowsForms/DataGrid/DataBinding.md
- WindowsForms/DataGrid/Filtering.md
- WindowsForms/DataGrid/GettingStarted.md
- WindowsForms/DataGrid/Selection.md
- WindowsForms/chart/Getting-Started.md
Have worked on changing title and description in ASP.NET Web Forms controls, please review.
Regards,
Yvone.
> SEO-181956 Windows Forms Title Identical

- WindowsForms/Pivot-Grid/Layouts.md
Have modified title, H1 and description, please review.
Regards,
Yvone.
> SEO-184192 Windows Forms Page with Redirect

- WindowsForms/DataGrid/Selection.md
Ticket ID : https://support.syncfusion.com/agent/tickets/616079
Hi @AmalRajUmapathySelvam ,
I have resolved the image issue reported in the above ticket. Please review the code changes and let me know if you any concerns.
> UG-616079 Image was not displayed properly in DataGrid Selection.

- WindowsForms/Visual-Studio-Integration/Template-Studio.md
1. The WinForms UG has been comprehensively updated to include sections on NuGet Entry, Dependency Injection (DI) Setup, PageServices integration, and details on managing Resource files. Additionally, existing content has been reviewed and refined to correct inaccuracies and eliminate duplicate information.
> WinForms Template Studio UG Improvements

- WindowsForms/Visual-Studio-Integration/Template-Studio.md
1. The WinForms and WPF UG has been comprehensively updated to include sections on NuGet Entry, Dependency Injection (DI) Setup, PageServices integration, and details on managing Resource files. Additionally, existing content has been reviewed and refined to correct inaccuracies and eliminate duplicate information.
> WinForms and WPF Template Studio UG Improvements

- WindowsForms-toc.html
Task - https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/187726/
> 187726 - Syncfusion License Validation Page Location Updated - Live

- WindowsForms/Calculation-Engine/Supported-Formulas/statistical.md
Added UG documentation of newly implemented statistical formulas in Calculate that are listed below:
1.  Gauss
2.  Gamma
3.  Var.S
4.  Frequency
> 905033-Added UG documentation of newly implemented Statistical functions of Calculate

- WindowsForms/Calculation-Engine/Supported-Formulas/Math-Trigonometry.md
Added UG documentation of newly implemented mathematical formulas in Calculate that are listed below:
1.  XLookUp
2.  XMatch
3.  FloorMath
4.  FloorPrecise
5.  IsoCeliing
6.  CeilingPrecise
7.  HStack
8.  VStack
9.  Phi
> 905033-Added UG documentation for newly implemented Mathematical functions

- WindowsForms/Calculation-Engine/Supported-Formulas/Text-Formulas.md
Added UG documentation of newly implemented text formulas in Calculate that are listed below:
1.  Unique
2.  TextAfter
3.  TextBefore
4.  ValueToText
5.  ArrayToText
6.  ToCol
7.  ToRow
8.  ChooseCols
9.  ChooseRows
10.  Sequence
11.  TextSplit
12.  Take
13.  Drop
14.  Expand
15.  WrapRows
16.  WrapCols
17.  Sort
18.  SortBy
19.  Filter
> 905033-Added UG documentation of newly implemented Text functions in Calculate

- WindowsForms-toc.html
Updated the UG documentation for Scrollbar customization for SFListView in Winforms.
> WPF 911926: Prepare UG document for AutoHideScrollBars visibility support for SfListView control in WinForms

- WindowsForms/Visual-Studio-Integration/Template-Studio.md
Need to update UG with NET9.0 changes for all below platforms:
1. Blazor
2. EJ2
3. MAUI
4. WPF
5. WinForms
> UG changes for NET9.0 for all platforms

- WindowsForms/System-Requirements.md
- WindowsForms/dotnet-framework-compatibility.md
NET 90 compatibility details updated in UG.
https://help.syncfusion.com/windowsforms/dotnet-framework-compatibility
https://help.syncfusion.com/windowsforms/system-requirements
> Net90 compatibility details updated

- WindowsForms-toc.html
- WindowsForms/PDF-Viewer/How-To/How to make Winforms PdfViewer have enriched features like WPF PdfViewer.md
- WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
**Description:**
Created UG for the How to section by adding separate UG content for the Hosting of WPF Pdfviewer in Winforms
*  This code change is for the UG for the Hosting of WPF PdfViewer in Winforms in the How to section of Winforms UG
*  Added detailed descriptions, examples, and guidelines for the UG for the Hosting of WPF PdfViewer in Winforms with code example.
* Added a seaparate md file for the UG for the Hosting of WPF PdfViewer in Winforms that is added as separate section in the How to section in Winforms UG
> 883468  - How to make Winforms PdfViewer to have enriched features like WPF PdfViewer.

- WindowsForms/DataGrid/Columns.md
**Description:**
I have updated the correct VB code for the "Columns" user guide documentation.
**Related PR:**
https://github.com/syncfusion-content/windowsforms-docs/pull/1109
> ES-923673 - Corrected the VB Code in the Columns user guide documentation

- WindowsForms/DataGrid/Columns.md
**Description:**
I have updated the correct VB code for the "Columns" user guide documentation.
**Related PR:**
https://github.com/syncfusion-content/windowsforms-docs/pull/1108
> ES-923673-Hotfix - Corrected the VB Code in the Columns user guide documentation

- WindowsForms/Calculation-Engine/Supported-Formulas/Financial-Formulas.md
- WindowsForms/Calculation-Engine/Supported-Formulas/Math-Trigonometry.md
- WindowsForms/Calculation-Engine/Supported-Formulas/Text-Formulas.md
- WindowsForms/Calculation-Engine/Supported-Formulas/statistical.md
Task ID : https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_backlogs/backlog/Tools%20Dev/Stories?workitem=925383
Prepared UG documentation for newly implemented formulas in 2024 Volume 4 release
**Statistical Functions**
Binom.Dist.Range
BetaDist
Trend
TINV
T.Test
T.DIST
TINV
T.Inv.2T
T.Dist.2T
T.Dist.RT
FTest
F.Test
F.INV
**Financial Functions**
XNPV
TBillPrice
TBillYield
Price
Yield
YieldMat
PriceMat
YieldDisc
OddLPrice
OddLYield
ODDFYIELD
ODDFPRICE
AMORLINC
TBillEq
PriceDisc
AMORDEGRC
**Mathematical Functions**
EuroConvert
**Text Functions**
BAHTTEXT
> 925383 - Prepare UG documentation for newly implemented formulas in 2024 Volume 4 release

- WindowsForms/Calculation-Engine/Supported-Formulas/Financial-Formulas.md
- WindowsForms/Calculation-Engine/Supported-Formulas/Text-Formulas.md
**Prepared UG documentation for the below functions:**
**Financial Functions**
1. XNPV
2. TBillPrice
3. TBillYield
4. Price
5. Yield
6. YieldMat
7. PriceMat
8. YieldDisc
9. OddLPrice
10. OddLYield
11. ODDFYIELD
12. ODDFPRICE
13. AMORLINC
14. TBillEq
15. PriceDisc
16. AMORDEGRC
**Text Functions**
BAHTTEXT
> 925383 - Added text and financial volume 4 functions

- WindowsForms/PDF-Viewer/Getting-Started.md
- WindowsForms/PDF-Viewer/How-To/View-the-PDF-stream-in-viewer.md
- WindowsForms/PDF-Viewer/Searching-Text.md
- WindowsForms/PDF-Viewer/Working-with-PDF-Viewer.md
- WindowsForms/PDF-Viewer/pdf-rendering-engines.md
Added the Trademark Symbol in md files
> Added the Trademark Symbol in md files

- WindowsForms/Add-Syncfusion-Controls.md
- WindowsForms/Control-Dependencies.md
- WindowsForms/Localization.md
- WindowsForms/Overview.md
- WindowsForms/System-Requirements.md
- WindowsForms/Testing/Coded-UI.md
- WindowsForms/Touch-Support.md
- WindowsForms/dotnet-core-compatibility.md
- WindowsForms/dotnet-framework-compatibility.md
- WindowsForms/theme-studio/theme-studio.md
[UG-936041](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/936041) Include Registered Trademark symbol for the common pages in WinForms UG
Include the Registered Trademark symbol for the common pages mentioned below in the WinForms UG document,
• System Requirements in Windows Forms - Syncfusion
• Overview of Syncfusion Essential Studio Windows Forms products
• .NET Framework & .NET Core Compatibility- Syncfusion WinForms controls
• .NET Core | Windows Forms | Syncfusion
• Control dependencies | Windows Forms | Syncfusion
• Getting Started With Windows Forms Theme Studio | Syncfusion
• Steps to add Syncfusion Essential Windows Forms controls
• Touch support for Syncfusion Windows Forms controls
• Localization in Windows Forms | Syncfusion
• Coded UI Testing | …
> UG-936041 Included the Registered Trademark Symbol in WinForms UG Document

- WindowsForms/Visual-Studio-Integration/Add-References.md
Title | Description
-- | --
|Task Category | Coverage Issues page with redirect links|
|Content Task Link/Mail Screenshot |NA|
|Hotfix |https://github.com/syncfusion-content/windowsforms-docs/pull/1161|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/196387|
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B941D3089-0C5C-4E47-9B04-5CC5E17E9060%7D&file=January%20-%202nd%20sprint.xlsx&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true|
Changes Made | Reason for change |
|-- | -- |
| Worked on redirect links | To avoid redirect links hence improving the performance of our page|
> SEO-196387--WinForms-Visual-Studio-Integration-Page-with-redirect-links

- WindowsForms/Overview.md
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr;border-width:100%'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr'>
Title | Description
-- | --
Task Link | IN -   198113 Updating Banner Content in Documentation
Feature description | To   update the content in the overview pages
Analysis and design | N/A
Output screenshots | N/A
Areas affected and ensured | Changes …
> Update Banner Content Dev

- WindowsForms/Overview.md
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>
<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>
<div style='direction:ltr;border-width:100%'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr;margin-top:0in;margin-left:0in;width:7.7416in'>
<div style='direction:ltr'>
Title | Description
-- | --
Task Link | IN -   198113 Updating Banner Content in Documentation
Feature description | To   update the content in the overview pages
Analysis and design | N/A
Output screenshots | N/A
Areas affected and ensured | Changes …
> Update banner content hotfix

- WindowsForms/PDF-Viewer/pdf-rendering-engines.md
**Description :**
- Updated the UG documentation of the WF PdfViewer for the newly generated Pdfium version
> 944821 - Updated WF pdfium UG to the new pdfium generated branch

- WindowsForms/Visual-Studio-Integration/Template-Studio.md
Update Windows Forms extension UG to Reflect Removal of .NET 6.0 and .NET 7.0 Support.
> Update extension UG to Reflect Removal of .NET 6.0 and .NET 7.0 Support

- WindowsForms/Syntax-Editor/syntax-highlighting.md
Checked and updated the configuration of custom language code snippet in EditControl.
https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/937060
> WF-937060 : Checked and updated the configuration of custom language code snippet in EditControl.

- WindowsForms-toc.html
- WindowsForms/PDF-Viewer/Working with ErrorOccured Event.md
Description :
Add the UG documentation about error occurred event
> 939394 :UG documentation about error occurred event in the WinForms PdfViewer

- WindowsForms/Calculation-Engine/Working-with-CalcEngine.md
Hi @MallikaRK 
|Title|Description|
|--|--|
|Task Category| Site Audit-Incorrect URL-format
|Content Task Link/Mail Screenshot| NA|
|UX task| NA|
|Hotfix|https://github.com/syncfusion-content/windowsforms-docs/pull/1211
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/200110/
|Excel/SharePoint link| NA| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B20474523-6AF0-4D8C-9BF4-5AF6C037651B%7D&file=Duplicate%20Title.xlsx&action=default&mobileredirect=true
|Changes made|Reason for changes|
|--|--|
|![image](https://github.com/user-attachments/assets/bf9e0935-3920-41c1-abac-56832dfacfaa)| To avoide redirection issue link of the page
Regards,
Mercy A.
> 200110-SEO-Site-Audit-Incorrect-URL-Format-Windowforms

- WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
Revamped the existing UG page for hosting the WPF pdfViewer in the WinForms application.
> Revamped the PdfViewer hosting details page

- WindowsForms/PDF-Viewer/How-To/How-to-make-Winforms-PdfViewer-have-enriched-features-like-WPF-PdfViewer.md
Revamped the existing UG page for hosting the WPF pdfViewer in the WinForms application.
> Revamped the WPF PdfViewer hosting details page

- WindowsForms/dotnet-framework-compatibility.md
[UG 957367](https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/957367): Need to update the .NET version compatibility page in WinForms documentation
Need to update the .NET version compatibility page in WinForms documentation
https://github.com/syncfusion-content/windowsforms-docs/pull/1223
[723796](https://support.syncfusion.com/agent/tickets/723796)
I have updated the .NET version compatibility page in WinForms documentation
> ES_957367 Hotfix Need to update the .NET version compatibility page in WinForms documentation

- WindowsForms/Visual-Studio-Integration/Template-Studio.md
Note content is not properly rendered in the Help documentation. So, modified the content under visual studio template topic.
> 971404 - Modified the notes content for General content

- WindowsForms/Docking-Manager/FAQ/MDIChild/How-to-avoid-flickering-while-creating-MDI-child-form.md
Updated the MDI Child Form flicker prevention documentation with necessary details
> WF-963841: Update the MDI Child Form flicker prevention documentation with necessary details

- WindowsForms-toc.html
[Task 976406](https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/976406): Remove Excel list from WinForms, WPF, WinUI, MAUI, EJ2 Core, EJ2 MVC, Blazor, Xamarin and  UWP
Remove Excel list from WinForms, WPF, WinUI, MAUI, EJ2 Core, EJ2 MVC, Blazor, Xamarin and  UWP
> 976406: Remove Excel list from WF

- WindowsForms-toc.html
- WindowsForms/dotnet-core-designtime-feature.md
Update the SDK package related details to the UG documentation.
https://dev.azure.com/EssentialStudio/Mobile%20and%20Desktop/_workitems/edit/979057
https://github.com/syncfusion-content/windowsforms-docs/pull/1308
> ES-979057 Update the SDK package related details to the UG documentation
